jarun/buku

- README.md
- buku
- buku.1
- Don't use ~/.cache, it's intended to store non-essential data files and may be purged at any time
- Instead, follow XDG and use $XDG_DATA_HOME or ~/.local/share/buku
- Fallback to current directory if HOME is not defined (Windows?)
> Fix database path

- README.md
- buku
- buku.1
Took me long enough, but I managed to merge it all. Having everything in a single file is not very practical for team work by the way ;-)
> Json output

- buku
continuing cleanup, now removed globals from UpdateEntry. More to come, but I'm breaking work in smaller chunks so they're easier to merge.
> UpdateEntry no globals

- tests/test_bukuDb.py
Initial testing infrastructure and some basic initial tests.
(Somehow I can't squash the commits, sometimes github really baffles me...)
> Adding tests

- buku
The change is simply an indentation of everything after the `if __name__` block. Github's diff seems to trip out, but I triple-checked with other diff programs and it's fine.
> moved main flow inside IF block, so that the module is importable

- buku
- at least two spaces before inline comment
- expected 2 blank lines, found 1
- too many blank lines (2)
- missing whitespace after ','
- missing whitespace around arithmetic operator
- whitespace after '{'
- whitespace before '}'
- multiple spaces before operator
- statement ends with a semicolon
- expected 2 blank lines, found 1
- unexpected spaces around keyword / parameter equals
- continuation line under-indented for visual indent
- blind except: statement
- comparison to None should be 'if cond is None:'
- comparison to True should be 'if cond is True:' or 'if cond:
- comparison to False should be 'if cond is False:' or 'if not cond:'
- bad indentation
- unused import readline
- unused argument 'argv'
- unused variable 'i'
- dangerous default value sys.argv (builtins.list) as …
> Flake8 fixes

- buku
See https://cryptography.io/en/latest/random-numbers/.
> Use system RNG in crypto

- README.md
- buku
- requirements.txt
PyCrypto is no longer maintained. Cryptography is an actively
developed library that provides cryptographic recipes and primitives.
See https://cryptography.io/.
> Switch from PyCrypto to cryptography

- buku
Makes parsing of -f output easier
> Use tab delimiter for -f N

- .gitignore
- .travis.yml
- tests/run_tests.sh
- tests/test_bukuDb.py
Added to https://travis-ci.org/poikjhn/Buku
I presume that adding to https://travis-ci.org/jarun/Buku may need be done from your account.
> Initial travis integration + two more tests

- buku
- buku.1
When any search flag (-s/-S/--st) is combined with
-d, the results can be deleted
> Add batch-delete feature

- tests/test_bukuDb.py
fixing test that would always pass
> fixed test_append_tag_at_index

- buku
- tests/test_bukuDb.py
> Revert "Some more tests, refactors for supplying input in tests"

- tests/test_bukuDb.py
* Added `test_append_tag_at_all_indices`
* Added `test_delete_tag_at_index`
* moving BukuDb instantiation to `setup` for DRYer code
* `setup` gets called for every test case, so a new BukuDb object is instantiated every time like before
* requires `self` to reference the BukuDb object now
* only relevant for the unittest test suite, does not affect the pytest cases
> 2 New tests, DRYing out BukuDb unit tests

- tests/test_bukuDb.py
* Added `test_search_by_tag`
* Added `test_searchdb`
* Some small refactors in testcases
* using helper functions to better represent what is being tested
* clearer syntax in a few places
> 2 New Tests, minor testcase refactors

- buku.py
Implementation of the first possible solution of issue #94
> Fix #94: Remove warning when adding HTTPS URL

- setup.py
> Fix UnicodeDecodeError when opening buku.py

- README.md
- auto-completion/bash/buku-completion.bash
- buku.py
by specifying --editor, this will open up an editor to edit, similar to how git commit message works.
This will be useful for long descriptions.
Currently only support adding
> An editor mode for adding and updating bookmarks

- buku.py
@Qu4tro provided this list of all APIs that could be supported in https://github.com/jarun/Buku/issues/113
In order to enable some of the following (specifically)
```
get     api/bookmarks     #get all bookmarks
delete  api/bookmarks     #delete table
```
I thought it was necessary to add some more functions to BukuDB. So before going on to writing the entire of the API, I wanted to observe what other BukuDB functions could come handy, and add them to this PR.
> BukuDB: Adding New Functions 

- buku.py
- tests/test_buku.py
- tests/test_bukuDb.py
fix the test from https://github.com/jarun/Buku/commit/e7bc397462fb4936e336c85fdfa90c2619865442#commitcomment-21688408
i'm not quite up to date with current code base, so it will take a while.
also i have seen the removed test from this commit 
https://github.com/jarun/Buku/commit/e7bc397462fb4936e336c85fdfa90c2619865442#commitcomment-21688408
i'm not quite sure the best strategy to test this and make the test easy and maintainable.
i will try use capsys for that.
i will also  browser test (if possible on this pr)
anything that i miss?
> fix: test: change test

- .travis.yml
- setup.py
Hypothesis should be lower bound instead of being fixed at 3.7.0
> reqs: Lower bound hypothesis

- .travis.yml
- tests/test_buku.py
- tests/test_bukuDb.py
> new: test: python3.6 on travis

- buku.py
- setup.py
- tests/test_buku.py
~~WIP~~
target
related issue #172
> refactor import db

- README.md
taken and edited from here https://github.com/jigneshpurohit/openshift_playbook/blob/7127518224d996e01a89db147434e404ebd35296/CONTRIBUTING.md
> add test documentation

- .travis.yml
- packagecore.yaml
A few notes, I'ved disabled centos for the time being.
There are errors unrelated to the setup (funny repo issues).
I've added your secure key and it should function fully upon
a new release tag. 
So currently a Debian (Ubuntu) package is created along with an
Archlinux package and a Fedora package. I see no errors but
this of course doesn't mean it is devoid of any errors.
> Add packagecore functionality

- packagecore.yaml
> packagecore fedora 26

- buku.py
This PR formats the entirety of `buku.py` docstrings in [NumPy style](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt).
I've tried to ensure that descriptions of parameters and return values are as clear, accurate, and specific as possible; however, please let me know if you notice anything that needs to be corrected or improved.
> Format buku.py docstrings in NumPy style.

- setup.py
Reverts jarun/Buku#204
We are keeping it the same.
> Revert "Update pypi summary"

- buku.py
> fix: test: logerr args

- buku.py
simple chromium support by using chrome bookmark parser
path for each os is taken from here 
https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md
> Chromium support

- README.md
Add instructions about how to install via pkg on FreeBSD.
> Add instructions about FreeBSD

- README.md
Add Gentoo package to the list
> Add Gentoo to packagers

- buku.py
- tests/test_bukuDb.py
Did you visit the [PR guidelines](https://github.com/jarun/Buku/wiki/PR-guidelines)?
--- PLEASE DELETE THIS LINE AND EVERYTHING ABOVE ---
> Add search_and_filter

- README.md
- buku.1
- buku.py
This improvement allows `buku` import and export org file.
> Import and export of orgfile

- bukuserver/README.md
> Added install paragraph

- MANIFEST.in
> chg: test: add yaml test file

- buku.py
Argument count (-n) is now respected when printing using "-p".
Current behavior is to show an interactive prompt (same as using -n with the other option like -s or -S).
> [Waiting for review]Added feature to respect -n when using -p

- MANIFEST.in
> add test file to MANIFEST

- auto-completion/bash/buku-completion.bash
- auto-completion/fish/buku.fish
- auto-completion/zsh/_buku
- buku
- bukuserver/filters.py
- bukuserver/server.py
- bukuserver/views.py
- tests/.pylintrc
- tests/test_buku.py
- tests/test_bukuDb.py
- tests/test_import_firefox_json.py
This pull request includes the following modifications:
- Long lines (≥ 140 characters) were split for better readability.
- Global variables that were still lowercase were made uppercase to clearly distinguish them from local variables.
- Minor improvements in syntax (removing superfluous parentheses, adding spaces where recommended by PEP8).
- Corrects a few typos (including: Unknonw → Unknown, firefox → Firefox, buku → Buku, and json → JSON where appropriate).
Please let me know if this is something you find useful. I read the PR guidelines and to the best of my knowledge, I believe I didn't break any rule.
Thank you for this great tool! As you would say in French, _merci beaucoup_ (meaning _thank you very much_, where _beaucoup_ sounds like Buku).
> Improve readability and fix minor typos.

- README.md
- auto-completion/bash/buku-completion.bash
- auto-completion/fish/buku.fish
- auto-completion/zsh/_buku
- buku
- buku.1
- bukuserver/filters.py
- bukuserver/server.py
- bukuserver/views.py
- tests/.pylintrc
- tests/test_buku.py
- tests/test_bukuDb.py
- tests/test_import_firefox_json.py
- fixes jarun/Buku#340
- replaced error with warning
- proper warning message added
- test added
> FIX(buku) #340 ff json import folder w/o children

- .gitignore
This project uses tox, which creates a directory of many virtualenvs in `.tox`.
> Add .tox directory to .gitignore

- buku
Use colorama to support better Windows colorizing
> Add better Windows color support using colorama

- buku
- tests/test_buku.py
> Revert "Feature/fix test"

- buku
> Revert "Add better Windows color support using colorama"

- README.md
- auto-completion/bash/buku-completion.bash
- auto-completion/zsh/_buku
- buku
Reverts jarun/Buku#383
We need to handle the `--preserve` option for auto-refresh, not regular update.
> Revert "Add --preserve option"

- README.md
Updates README.md with another installation option on macOS via MacPorts.
> Add macOS/MacPorts as a packager

- tests/test_bukuDb.py
follow up on #405 & #407
maybe wait till @stkw0 	can verify it before merge
> fix: dev: use modified safe loader

- Dockerfile
- MANIFEST.in
also modififed docker build
Signed-off-by: Ameya Shenoy <shenoy.ameya@gmail.com>
> fix(manifest): include static files in manifest

- .circleci/config.yml
Signed-off-by: Ameya Shenoy <shenoy.ameya@gmail.com>
> build(docker): build docker image and push to hub

- buku
This PR adds a comment per line in `.md` files that includes the tags
```md
* [Title](url) 
```
I could add this to `.org` mode too, but I'm not familiar with the syntax.
Closes #418
> Export tags in markdown format as comments

- bukuserver/server.py
> use ImportError instead ModuleNotFoundError

- README.md
- auto-completion/zsh/_buku
- buku
Add optional file arg to json output arg to read output with another command #447
> resolves #447, add optional file arg to json output arg

- bukuserver/bookmarklet.js
- bukuserver/server.py
- bukuserver/templates/bukuserver/home.html
- bukuserver/views.py
Following suggestions in https://github.com/jarun/buku/issues/385#issuecomment-498965554 by @zoredache I implemented this BookmarkletView which checks if the url already exists and redirect to edit or new.
I then added this bookmarklet to send the url, the title and the selected text as description to this new BookmarkletView in bukuserver (up to 4000 chars, as inspired by shaarli's bookmarklet).
I also added the bookrmarklet install instructions to the Home page (I couldn't find a better place). 
The bookmarklet is working pretty good in my tests.
This is my first contribution here, so hopefully it captures the idea. Any comments to improve the PR are welcome.
> add bookmarklet (#385)

- buku
- tests/test_bukuDb.py
this also include example for buku record and type hint for print_single_rec
> simplify test_update_rec_update_all_bookmark

- bukuserver/views.py
> fix: dev: index error on bookmark

- bukuserver/views.py
- tests/test_views.py
temporary fix until actual cause found
> fix: bukuserver bookmark creation

- buku
- tests/test_BukuCrypt.py
Same problem as 58c2ae2, finalizing in a loop.
> Fix decrypt_file

- tox.ini
Did you visit the [PR guidelines](https://github.com/jarun/Buku/wiki/PR-guidelines)?
--- PLEASE DELETE THIS LINE AND EVERYTHING ABOVE ---
> tox python39

- Dockerfile
based on comment here 
https://github.com/jarun/buku/issues/501#issuecomment-779401110
~~and pr here~~
~~https://github.com/linuxserver/docker-limnoria/pull/5~~
> docker CRYPTOGRAPHY_DONT_BUILD_RUST

- bukuserver/README.md
- bukuserver/server.py
- tests/test_server.py
add function to get boolean from env var.
unfortunately change requested here can't be done, because flask.jsonify can't use generator, at least pylint error will be gone
https://github.com/jarun/buku/commit/f1c42de7929bd5e054ce61cabd6548b900b34bc8
> server update

- bukuserver/views.py
Noticed that the 'not contain' filter wasn't working properly
> fix bug in views.py

- .pre-commit-config.yaml
- buku
- bukuserver/requirements.txt
- setup.py
- tests/test_buku.py
- fix r1714 pylint
- update pre commit
- test buku is black formatted
- change required package for server based on https://github.com/aws/aws-sam-cli/issues/3661#issuecomment-1044340547
> fix r1714 pylint and pre commit

- tests/test_buku.py
> test: xbel

- bukuserver/filters.py
- bukuserver/views.py
fixes #618:
* fixing incorrect handling of plain search requests by the main page search form handler
* fixing server error on empty search in the same handler
also fixes #625 (see LeXofLeviafan#1)
> [bukuserver] Plain search request fix

- README.md
- buku
- buku.1
> Improved Vivaldi support

- bukuserver/templates/bukuserver/bookmark_create_modal.html
- bukuserver/views.py
related to #564 (partial fix?):
* adding "Save and Add Another" & "Save and Continue Editing" buttons to Create New Record modal (redirecting to `/bookmark/new` & `/bookmark/edit` pages respectively)
> [bukuserver] Create & redirect buttons

- README.md
- buku.1
based on conversation here
https://github.com/jarun/buku/issues/639
i don't know if it is good enough
the pr is big enough but the change is minimum
> add example to show simple bookmark addition and unique url feature

- buku
Fixes #682 (patch applied from there)
> Fixed Windows profile detection

- bukuserver/requirements.txt
- requirements.txt
- setup.py
fixes #686:
* imposing version range limit on Flask & urllib3 dependencies (thus avoiding compatibility issues in deps)
> Dependencies fix

- requirements.txt
- setup.py
`colorama.just_fix_windows_console()` [was only added in v0.4.6](https://github.com/tartley/colorama/blob/master/CHANGELOG.rst)
> [jarun#704] fixing required colorama version

- tests/test_buku.py
- tests/test_bukuDb.py
> fix htttp typos via `s/htttp/http/g`

- README.md
https://git.xmpp-it.net/sch/BukuBot
> Add project BukuBot to section related projects

- bukuserver/templates/bukuserver/bookmark_create.html
- bukuserver/templates/bukuserver/bookmark_create_modal.html
- bukuserver/templates/bukuserver/bookmark_details.html
- bukuserver/templates/bukuserver/bookmark_details_modal.html
- bukuserver/templates/bukuserver/bookmark_edit.html
- bukuserver/templates/bukuserver/bookmark_edit_modal.html
- bukuserver/templates/bukuserver/bookmarks_list.html
- bukuserver/templates/bukuserver/home.html
- bukuserver/templates/bukuserver/lib.html
- bukuserver/templates/bukuserver/tags_list.html
A minor adjustment of where keyboard focus ends up when loading a page/opening a modal (for better UX)
> fix autofocus

- bukuserver/templates/bukuserver/tag_edit.html
- bukuserver/views.py
…Missed the tag edit form in #767 :sweat_smile:
> fix autofocus in tag edit form

- bukuserver-runner/README.md
- bukuserver-runner/buku-server-headless.desktop
- bukuserver-runner/buku-server.desktop
- bukuserver-runner/buku-server.py
The cross-platform Python implementation of a Bukuserver runner tool (as discussed in #764).
Also added two `.desktop` file templates (which can be used in Linux), and a user guide.
> added a bukuserver runner tool

- buku.1
Fix reference to non-existant flag
> Typo in manpage buku.1

- buku
fixes https://github.com/jarun/buku/issues/821
Couldn't test on Windows.
Tested on Linux with an empty `HOME` variable.
> check if variables are empty if set.

- README.md
- buku.1
resolves #649:
* adding a mention of library API to the feature list in manpage & readme (with a link to API docs in the latter)
also:
* adding a mention of Bukuserver + HTTP API to the feature list (with a link to the project wiki page in readme)
* fixing discrepancies between feature lists in manpage & readme (except for auto-import line which is done in #849)
> Mentioning library API & companion Web-app in features list
