jarun/buku

- buku
1. Use argparse instead of getopt.
2. Use argparse features to reduce redundant options, arguments.
3. Simpler short options wherever applicable.
4. Add long options.
5. Update documentation.
> Switch to argparse

- buku
- tests/test_bukuDb.py
* `delete_bookmark` returns `True` instead of implicitly returning `None`
* will return `None` if deleting all bookmarks and user input is not "y"
* this is for testing purposes
* added `test_delete_bookmark_yes`
* added `test_delete_bookmark_no`
* added `()` to caplog.records call
Making use of the `unittest`'s `mock` module, specifically `mock.patch` to mock user input. This should be a much better solution than having to pass in input functions to API methods.
> Two tests, minor method call fix

- buku
- tests/test_bukuDb.py
* Using `unittest.subTest` to make sure assertions inside each iteration are tested, even if earlier ones fail.
* Moving select_tag_from_bookmarks back into append_tag since; not really useful since input functions aren't being passed to methods. This also maintains more symmetry with other similar methods.
> Testing enhancements

- tests/test_bukuDb.py
Affects
* `test_searchdb`
* `test_search_by_tag`
Fixed issue where tests would pass for cases in which they should fail.
> fix test_search* cases

- tests/test_bukuDb.py
* `test_open_all_in_broswer`
* Better worded comments in tests comparing result sets from search
* `browser_open` is now `open_in_browser`
> One new test, rename broswer_open in tests

- buku
Just a little update to add the possibility to print "title" only.
For me, it's simpler to get an overview of my bookmarks with title than URL. 
I think it's better to add this option as N=2. Like that, N=1 and N=2 export only a field and N=3 two fields. To avoid regression, I add it as N=3.
> Add "show only title" as format option.

- buku
I tried running "buku --help | less" to better view the --help page, but to find that it doesn't work. --help is going through sys.stderr rather than sys.stdout. I'm not sure if there was a reason for this, but it's highly unusual.
> Change --help output to STDOUT rather than STDERR

- buku.1
- buku.py
Hi, I would like to be able to use Buku behind an enterprise proxy. urllib3 already has support for that, but need to be configured when creating an pool manager. This patch does that configuration. All that is needed is some environment variables (http_proxy, https_proxy, etc) that are already nsed by other tools, such as curl, wget, etc.
> Support http proxy environment variables

- buku.py
I included two versions of refreshdb.
The first one uses one connection per thread, and the second one has the threads share a single connection
I added the timeout and check_same_thread args to all sqlite3.connect statments   
timeout was to prevent a thread from locking the DB while waiting on another thread. 
check_same_thread was supposed to let me share a connection across threads
I get them same error for both the single connection and multi-connection versions
sqlite3.ProgrammingError: Cannot operate on a closed cursor.
While playing around I got some similar errors 
sqlite3 ProgrammingErrors : Can't operate on a closed database. 
sqlite3.OperationalError: database is locked
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.
Also, you …
> draft: multithreaded refreshdb

- auto-completion/zsh/_buku
fixes
`_arguments:comparguments:319: invalid option definition: (-f --format)-f[limit fields in print and Json output:value`
in ZSH autocompletion file
> fixed ZSH syntax error for auto completion

- buku.py
Description
Press `Ctrl-C` while buku is reading from input() (e.g. at the prompt). The terminal does not reflect input after buku terminates.
Solution overview
This solution disables the sig handler temporarily when we are reading input and resume after.
This works by providing a read_input() wrapper that disable the sig handler before reading from input and enables it after input is read.
> Disable sig handler when reading input

- buku.py
Tested on Vivaldi (Chrome-based), qutebrowser (PyWebKit-based), Pale Moon (Firefox fork) and Firefox Developer Edition. It works as intended *if* the current default browser (or whatever Buku thinks the default browser is) is actively running. Depending on the browser, it still only opens everything in one tab if it is *not* running yet. But who closes his browser anyway? :-)
> Threading for webbrowser on Win32 (partially fixes #142 for good).

- tests/test_bukuDb.py
fix index test on print_rec
cmiiw when `index` is negative it will use `low`, `high` index. 
`high` is max id and `low` is either 1 when absolute value of index greater equal than max id or index counting down from max id.?
low = (1 if _id <= -index else _id + index + 1)
also we should set `$CI_FORCE_TEST` to true so travis will always run test everytime commit uploaded.
on the last build here https://travis-ci.org/jarun/Buku/jobs/226180363
None of the watchlist items changed, skipping tests.
You may set the $CI_FORCE_TEST environment variable to force testing
the test is skipped, because commit didn't change the watched files (buku.py, tests, travis.yml)
> chg: update test

- README.md
- buku.1
- buku.py
This commit adds an additional format option ```-f 4```, which provides the fields: url, title, and tag in the output. This combination, was the only one missing from available format options which contains every other permutation of these three fields except for this one.
While the default format does contain the same fields, this format is needed because it (and the other format options 0-3) are very script friendly, whereas the default is not.
Sample output:
```
> buku -p -f 4
1	https://github.com/jarun/Buku#gui-integration	GitHub - jarun/Buku: Highly delicious bookmark manager. Your mini web!	
2	https://github.com/jarun/Buku	GitHub - jarun/Buku: Highly delicious bookmark manager. Your mini web!	bookmarks,cli
3	http://www.techrepublic.com/article/lesser-known-linux-commands-join-paste-a …
```
> add aditional format option to print url, title, and tag

- buku.py
This fixes an incorrect docstring description of the return value of `prep_tag_search`. Previous version stated incorrectly that the return value of `prep_tag_search` was None if ` - ` was not present in the `tags` argument. But it's actually only the third element in the returned tuple that would be None in that case.
> Fix incorrect docsting in prep_tag_search

- buku.1
In the `EXAMPLES` section of the man page, there are several example subsections where two example cases are listed back to back. E.g.:
```
buku -w
buku -w 'macvim -f' -a https://ddg.gg search engine, privacy
```
However `.br` breaks are missing from these cases, and the examples display on a single line:
`buku -w buku -w 'macvim -f' -a https://ddg.gg search engine, privacy` 
This PR adds `.br` breaks to make new lines to separate these cases.
> Add breaks between lines in man page examples

- requirements.txt
Removes unnecessary addition of `recommonmark` dependency to `requirements.txt`
> Remove recommonmark from requirements.txt

- docs/source/index.rst
Keeps RTD documentation up to date with the current package summary.
BTW, the RTD `latest` branch is still accessible. Did you decide to keep it or should it be set to private? (It might also be able to be set to 'inactive').
> Update RTD index with proper package summary

- buku.py
With this PR Firefox autoimport gets default profile from `profile.ini` file, and fix one bug in `load_chrome_database` function.
> Get default profile path from profiles.ini file

- README.md
- buku.1
- buku.py
- tests/test_buku.py
Following the discussion in https://github.com/jarun/Buku/issues/214, this PR implements a `print_rec_with_filter` function, which is called when the `--format` option is used with search options. E.g., `buku -f1 -t programming`. This fixes the current behavior where the filter is ignored when used with search options.
In addition,  this simplifies the blocks in `print_rec` that check the field filter and print the results. 
Adds field filters, `10`, `20`, `30`, `40`, which correspond to filters `1`, `2`, `3`, `4` but omit the DB index from the printed results.
A unittest, `test_print_rec_with_filter`, is added in `test_buku.py`. 
Help page, man page, and README me are updated accordingly.
> Search honors field filters: implements print_rec_with_filter

- buku.py
This PR uses set() instead of a for loop to create a list of unique tags in the `parse_tags` method. This eliminates the need for some condition checks and variable assignments.
Part of the bookmark add path optimization discussed in https://github.com/jarun/Buku/issues/223
> Use set() to create list of unique tags in parse_tags method

- README.md
Adding Pinku, a Pinboard-to-Buku importation utility to the Related Projects section of the README
> Add Pinku to Related Projects in README

- buku.py
- tests/test_bukuDb.py
This PR uses set operations to remove some conditional checks, loops, assignments in the `suggest_similar_tag` method.
Also, I didn't see a test for this method so I added a `test_suggest_tags` test in `test_bukuDb.py`.
> Use set operations in suggest_similar_tag method; add tests

- tests/test_bukuDb.py
related: https://github.com/jarun/Buku/commit/3c7856950846c47804d59cba1475a63a40b2e29a
i can't think anything about which can caused this. i suggest just print the caplog's records and fix if any other bug reported related to this happen on user with python3.4
> chg: test: add exception on python3.4 tests

- setup.py
- tests/test_bukuDb.py
simple test for the method
also looking at documentation optional method paramater should have default value.
this also raise problem because variable `stag` which is not optional come after optional paramater
example
```python
def search_keywords_and_filter_by_tags(self, keywords, all_keywords=True, deep=True, regex=True, stag=None):
"""doc"""
stag = stag is stag is not None else stag
...
``` 
e: also change pytest version because recent pytest fail
failed pytest version: pytest-3.5.0
travis: https://travis-ci.org/jarun/Buku/jobs/357205570
recent passed pytest version: pytest-3.4.2
travis: https://travis-ci.org/jarun/Buku/jobs/357157044
e2:error from travis
```shell
$ python3 -m pytest ./tests/test_*.py --cov buku -vv
Traceback (most recent call last):
File …
```
> test for search_keywords_and_filter_by_tags method

- buku.py
- tests/test_bukuDb.py
Issue: Support keyword filtering (records having keywords a and b but not c and d)
There is one new method I added to BukuDB called `exclude_results_from_search`.  I added a cli parameter "-W --without" which does a keyword search using searchdb and subtracts those results from the already completed search_results.
I followed your style and form from last commit (sorry, 1st pull request a bit sloppy).
Added tests.  Travis passing.
> Support keyword filtering (records having keywords a and b but not c and d)

- bukuserver/templates/bukuserver/statistic.html
related #267 
- netloc is now using simple anchor tag instead of form 
- not tested on `No Netloc` entry
- just recently found out that the netloc search may not accurate. click on `twitter.com` will search any bookmark with `twitter.com`, or `mobile.twitter.com` because it is using regular search. 
out of topic, any plan to add netloc search @jarun?
not sure if people want it, but if feature exist in future, the logic here must be changed
> clickable link on chart

- bukuserver/server.py
- bukuserver/templates/bukuserver/statistic.html
(maybe) the last part of statistic
this include
- change to number. now it is right aligned for better view
- fix for title which positioned incorrectly
- entry for `No title` is also calculated but not linked to bookmark search
> title statistic

- setup.py
Also, in some Linux distros like Gentoo it's forbidden to install a package with the name "tests"
> exclude tests package from installation

- setup.py
how to recreate the bug
- create distribution file `python setup.py sdist`, result is dist/buku-4.0.tar.gz
- on empty folder create empty virtualenv
- pip install from tar.gz file
- error below
```python
Processing /home/username/git/Buku/dist/buku-4.0.post1.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-req-build-hdfr3v1h/setup.py", line 13, in <module>
shutil.copyfile('buku', 'buku.py')
File "/home/username/envs/temp/lib/python3.6/shutil.py", line 120, in copyfile
with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'buku'
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-hdfr3v1h/ …
```
> fix setup script

- buku
buku --ai couldn't find profile for Firefox 52 on macOS 10.14. 
the profiles.ini looks like this:
[General] 
StartWithLastProfile=1
[Profile0]
Name=default
IsRelative=1
Path=Profiles/<REDACTED>.default
this patch adds ability to handle this.
> Fix autoimport for firefox

- bukuserver/README.md
- bukuserver/server.py
- bukuserver/views.py
implementation rational
* the access via `current_app.config` was modeled after the way how `BUKUSERVER_PER_PAGE` and `BUKUSERVER_URL_RENDER_MODE` was used. But you're right, access function is cleaner
* access to `bukudb` in `StatisticsView` was modeled after `BookmarkModelView`: there `bukudb` was referenced via positional argument, additional ones (`page_size`) was then accessed (and removed) via `kwargs` 
* if the env var is not set, `getenv` returns `None`, which, when used for the ctor of `BukuDb` as `dbfile` parameter, triggers the default behaviour. Therefore I did not add any checks.
> NEW(server) add db path option

- tox.ini
The `tox.ini` file had a few updates to get it working again:
- We can delete the commented lines, because they have already been kept inside of the Git history.
- tox does not support pipe characters in commands (https://bitbucket.org/hpk42/tox/issues/73), so we use `find -exec` and remove `xargs`
- We ignore the `.tox` directory for linting to avoid catching a bunch of imported code.
> Update tox.ini to work locally

- buku
- buku.1
Simple modification to add an addition `--format` option to only print the title and tags.
> Add ability to print only title and tags with the --format option

- buku
fix #361 
to use custom certificate set `BUKU_CA_CERTS` env variable to your certificate path.
@ranebrown
@jarun it is simplest config i can think of. other alternative is to create parameter  for custom certificate but it require to refactoring buku. 
e: also no test for now, if i find method on how to check custom certificate, i will add it later
> new: dev: use custom ca certs

- requirements.txt
this is to let requirements.txt list the package on setup.py. this way there is only single place to update package (setup.py)
reference
https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py
at first i thought this can be replaced with single dot character, but `setuptools` actually a bit trickier
there is an alternative on how to install setuptools at link below but it is a lot more (unnecessary) work just to replace the requirements.txt
https://stackoverflow.com/a/48129284/1766261
so in the end setuptools is stay as required package on requirements.txt and other package will be listed on setup.py
> chg: dev: requirements.txt

- tests/test_bukuDb.py
fix #371 
there are several behaviour change on python 3.7 (and maybe for future python version)
- caplog have to set manually to debug level
- the way we have test with using logging is depend on how the function generate it. so if it change even a little bit (comma, period, newline, etc) it will require change to test
- please see the db sql line. i have no idea why it is changed and different from the old python version
e: can't find where the debug level change on pytest's caplog but the solution is taken from here https://github.com/pytest-dev/pytest/issues/3226
e2: look like there is a change on search_by_tag_query argument
> Feature/fix python3.7

- README.md
- auto-completion/bash/buku-completion.bash
- auto-completion/zsh/_buku
- buku
Adds preserve option like in [#327](https://github.com/jarun/Buku/issues/327).
> Add --preserve option

- bukuserver/README.md
- bukuserver/views.py
fix #394 
this is will not change default behaviour because user can open new tab by ctrl+click, middle click, or other way. but this will give user option to enable this as default.
> new: user: open in new tab

- tests/test_bukuDb.py
follow up on #405 & #407
if @stkw0 can verify it, @jarun, you can just merge it even if labels haven't been changed
other alternative can be seen here https://stackoverflow.com/questions/22834392/understanding-too-many-ancestors-from-pylint
but i choose this one as this is only occur once
> fix: test: ignore too many ancestor error

- Dockerfile
- bukuserver/README.md
Also added related docs. It is worth mentioning that at this point the
server used inside the docker container is the default Flask server,
which is not production ready.
Edit: modified Dockerfile to serve requests with `gunicorn`
Linked to #410
> feat(docker): add Dockerfile to build container

- bukuserver/filters.py
- bukuserver/views.py
- tests/test_views.py
related #424
this actually only restore the change from 6bfe5050bc81f185b0c38198a080077a788fcfdb 
on that discussion i offer to change it to dict but looking at the filter method, it require to change flask_admin's `_filter` method which make it more complicated.
https://github.com/jarun/Buku/blob/467d865e420a11c5a5f858a83f38bd9d5b3abd82/bukuserver/views.py#L355
so it is keep as list. 
minor change is a default sort for that list, because dict.items in python 3.5 will return result in different order
also added type hint and test for `get_list` method
e: just found about the bug source on model view. fix added to pr
> fix tag model view

- buku
- differentiate function input and function variable when the type is changed (`tags` and `tags_`)
- ignore mypy error on `readline`
---
on #429 i wrote
> for prep_tag_search maybe instead None, None, None return '', '', ''. this will keep Tuple[List[str], str, str] as return type and will not produce error.
but after testing it, i just change first item so second item and third item can still be `Optional[str]` and not change too much on `search_by_tag` function
with this running mypy on the file, should not produce any error
> type hint for function

- bukuserver/README.md
- bukuserver/requirements.txt
- bukuserver/server.py
- setup.py
related #415
e: to use it
- install flask-reverse-proxy-fix `pip install flask-reverse-proxy-fix`
- set `BUKUSERVER_REVERSE_PROXY_PATH`
- note from flask-reverse-proxy-fix: The prefix value SHOULD include a preceding slash, it SHOULD NOT include a trailing slash (i.e. use /foo not /foo/).
> reverse proxy

- buku
- tests/test_buku.py
Description: This PR adds support for tags for Org-Mode import/export. According to Org-Mode syntax, tags are added at the end of a line as a list of colon separated keywords:
* [[url][title]] :tag1:tag2:
No new dependencies were added, and I have tested import and export of bookmarks with and without tags without problems.
I only changed the code for Org import/export, and the displayed help message, so I don't expect any side effects.
> Org tag support

- buku.1
The primary purpose of this PR is to fix the unescaped backslashes in the manpage on line 31 (it was rendering as `%APPDATA%kmarks.db` instead of `%APPDATA%\buku\bookmarks.db`).
I also took the opportunity to fix some other minor typographical issues in that area.
> Fix some minor typographical issues in manpage

- buku
- tests/test_buku.py
change buku tags to org mode tags convertion
related issue #469
old rules:
- add additional whitespaces for tags that end or start with a colon
- if colons are inside a tag, add one additional colon
new logic:
1. any character which don't match `[a-zA-Z0-9_@]` will replaced with space character
2. multiple whitespaces will be replaced with underscore character
3. only unique tags will be returned in ascending order
it will break logic from previous version.
only simple test case and a single tag based on related related issue
> buku tags to org mode tags

- buku
- tests/test_buku.py
fix #466, especially import_md and import org
this also include
- simpler tacit var check and generated question
- type hint for import function
- updated test
i noticed that python 3.5 is already reached end of life, so maybe remove that python version on circle ci?
e: i only check md, org mode and html. i may (or may not) check json later
> fix import 

- buku
Two bugs:
- When padding data, `chunk`'s type was changed from bytes to str.
- `encryptor.finalize` was called in a loop, causing `AlreadyFinalized` whenever there are more than one chunk.
To reproduce old bugs:
Use a file larger than `CHUNKSIZE` (512KiB):
```console
$ ln buku buku.py
$ dd if=/dev/zero bs=1024 count=513 of=data
$ python3 -c 'import buku; buku.BukuCrypt.encrypt_file(8, "data")'
Password:
Password:
Context was already finalized.
```
Similarly, to reproduce the padding bug, just create a file that's not a multiple of 16 bytes. I think this buggy code path wasn't ever triggered due to SQLite databases always being full blocks.
> Fix BukuCrypt.encrypt_file

- .pre-commit-config.yaml
- buku
- setup.py
- tests/test_bukuDb.py
- delete_rec: index have default None value
- delete_rec: remove the table only when index is 0 instead of None based on index check
- delete_rec: index is now optional based on numpy definition
- delete_rec: no recommendation to use dummy index on is_range description. also no default value as it is stated on function definition
- delete_rec: example
- delete_rec: parameter check is changed see below for more 
- print_rec: description on database check
- print_rec: no recommendation to use dummy index
- print_rec: remove description of default value on is_range as it is stated on function definition
- print_rec: example
- print_rec: section on negative index only run when is_range is False
- setup: pytest vcr for vcr integration
- test_bukuDb: black formatted
- test_bukuDb: …
> update print_rec and delete_rec

- buku
- setup.py
This PR reflects the proposal from issue #516.
This only affects Linux distros which use `openssl`, with the consensus is '/etc/ssl/certs/ca-certificates.crt'. BSD systems that utilize `libressl` might have a different hardcoded path that I don't know about.
> Use system ca-certificates if it exists on Linux

- bukuserver/static/bukuserver/js/Chart.js
- tests/test_bukuDb.py
There are small typos in:
- bukuserver/static/bukuserver/js/Chart.js
- tests/test_bukuDb.py
Fixes:
- Should read `should` rather than `shold`.
- Should read `containing` rather than `containg`.
- Should read `bookmark` rather than `boomark`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- buku
- tests/test_buku.py
See issue ticket for the feature being implemented.
Basically, so far only one parent folder was added as tag to a bookmark.
Now, every parent folder (in nested structure) will be added as tag/label to the bookmark. 
Folder lookup changed to a relatively safe one that also able to do the work recursively.
Multiple branches to test if they influence each other (they shouldn't).
Some why when using find_parents('dt'), it found folders from other branch, when tested with my own data set.
> [#539] Add nested folder structure tagging in import_html

- docs/source/bukuserver.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/modules.rst
- setup.py
- update for documentation using sphinx
- package is based from poetry 
- modules is based from sphinx-apidoc
- python file is formatted with darker
related https://github.com/jarun/buku/issues/484#issuecomment-1053723683
```shell
> # install required package
> pip install -e ".[docs]"
> # clone buku wiki
> git clone https://github.com/jarun/buku.wiki.git docs/source/wiki
> # build documentation
> sphinx-build docs/source build
> xdg-open build/index.html
```
---
i said to try mkdocs but there is also problem with it 
https://github.com/rachmadaniHaryono/Buku/tree/feature/mkdocs
i haven't going too deep to it but i may not continue it if sphinx can be used
i still don't know how to upload it to github page or readthedocs
> docs update

- tests/test_views.py
just change the data for the test, will test on actual bukuserver later
unrelated but there are following warning
```python
../../../../home/r3r/.pyenv/versions/buku/lib/python3.10/site-packages/flask_api/renderers.py:4
/home/r3r/.pyenv/versions/buku/lib/python3.10/site-packages/flask_api/renderers.py:4: DeprecationWarning: '_request_ctx_stack' is deprecated and will be remoevd in Flask 2.3.
from flask.globals import _request_ctx_stack
../../../../home/r3r/.pyenv/versions/buku/lib/python3.10/site-packages/flask_admin/form/widgets.py:2
/home/r3r/.pyenv/versions/buku/lib/python3.10/site-packages/flask_admin/form/widgets.py:2: DeprecationWarning: '_request_ctx_stack' is deprecated and will be remoevd in Flask 2.3.
from flask.globals import _request_ctx_stack
```
i tried to add following …
> fix(test_views): test data for tag_model_view

- buku
I've checked the ToDo list and [PR guidelines](https://github.com/jarun/Buku/wiki/PR-guidelines).
Remove the DeprecationWarning `'cgi' is deprecated and slated for removal in Python 3.13`.
See possible methods in #604, I choose to replace `cgi` with `email`.
None since `cgi` and `email` are all standard libraries (https://docs.python.org/3.11/library/email.html).
I cloned the repo, made a fix and installed the updated buku using `python setup.py install` inside an isolated virtualenv and it does not show the deprecation warning anymore. The linting test running locally with `python3 -m pylint buku` passed as well.
Didn't touch as I think it's not related.
> Remove `cgi` DeprecationWarning (Close #604)

- bukuserver/static/bukuserver/css/bookmark.css
- bukuserver/views.py
fixes #607
* adding spaces between tags in a single bookmark view (only the details modal/page appears to be affected)
* preventing layout overflow in tables (by ensuring that long lines wrap)
* increasing bookmark modals width (getting it closer to list width, thus improving viewing experience for long lines)
> [bukuserver] Bookmark details overflow fix

- bukuserver/static/bukuserver/js/last_page.js
- bukuserver/views.py
fixes #606:
* implementing a generic `/last-page` endpoint handler (for any `BaseModelView` subclass)
* overriding the last-page pagination link at runtime
* applying both to bookmark & tag lists
* also chainging the redirect in `/tags/refresh` handler to retain consistency.
> [bukuserver] Last page endpoint

- bukuserver/README.md
- bukuserver/server.py
- bukuserver/views.py
fixes #549:
* adding a `BUKUSERVER_READONLY` boolean environment variable
* implementing a generic editing disabler for a model based on the value of said variable
* applying said disabler to bookmark & tag models
also:
* improving description of `DISABLE_FAVICON` (for clarity)
* adding a space after the bookmark favicon for visual improvement
> [bukuserver] Readonly mode

- bukuserver/README.md
- bukuserver/forms.py
- bukuserver/server.py
- bukuserver/templates/bukuserver/bookmark_details.html
- bukuserver/templates/bukuserver/bookmark_details_modal.html
- bukuserver/templates/bukuserver/statistic.html
- bukuserver/views.py
- tests/test_views.py
fixes #635:
* renaming the `url` param to `link` in HTML forms & queries (excluding the API)
also:
* clarifying the purpose of `BUKUSERVER_SECRET_KEY` (in readme)
* normalizing filter parameter indices in `statistic.html` (see #624)
* fixing `BUKUSERVER_OPEN_IN_NEW_TAB` (broken in current master)
* fixing [Little Bobby Tables](https://xkcd.com/327) (as well as incorrectly encoded values)
* adding custom formatting to details page/modal (linebreaks, hyperlink in **Url** field)
> [bukuserver] Non-conflicting URL parameters in GUI

- bukuserver/templates/bukuserver/bookmark_edit.html
fixes #640:
* adding a delete button to the bookmark edit page (based on [the row action button](https://github.com/flask-admin/flask-admin/blob/v1.6.0/flask_admin/templates/bootstrap3/admin/model/row_actions.html#L25-L38))
> [jarun#640] reproduced delete button on bookmark edit page

- .gitignore
- bukuserver/README.md
- bukuserver/api.py
- bukuserver/bookmarklet.js
- bukuserver/forms.py
- bukuserver/server.py
- bukuserver/static/bukuserver/js/flash.js
- bukuserver/templates/bukuserver/bookmark_create.html
- bukuserver/templates/bukuserver/bookmark_create_modal.html
- bukuserver/templates/bukuserver/bookmark_details.html
- bukuserver/templates/bukuserver/bookmark_details_modal.html
- bukuserver/templates/bukuserver/bookmark_edit.html
- bukuserver/templates/bukuserver/bookmark_edit_modal.html
- bukuserver/templates/bukuserver/bookmarks_list.html
- bukuserver/templates/bukuserver/home.html
- bukuserver/templates/bukuserver/lib.html
- bukuserver/templates/bukuserver/statistic.html
- bukuserver/templates/bukuserver/tags_list.html
- bukuserver/views.py
Several commits with co-dependent code.
fixes #639:
* preventing override of POST data by URL arguments in `create_form()`
* adding metadata collection to the bookmarklet (when no text is selected)
* implementing a checkbox allowing to disable automatic fetching of empty fields (placed under the submit buttons)
* fixing saved link in the success alert (so that it works correctly in the form page)
* automatically closing any of the primary pages if opened in popup window (so that it works like a modal dialog)
* hiding/blocking primary page links in popup window (in the "refactoring" commit)
* handling DB rejection in `create_model()` (producing custom error message)
fixes #642:
* disabling hyperlinks for URLs without netloc (in list & details)  
_note: URL parser works differently in JS, …
> [bukuserver] Bookmarklet, optional fetch, refactor

- bukuserver/README.md
- bukuserver/server.py
fixes #644:
* adding an env variable to supply a theme name (from [this list](https://bootswatch.com/3)) [to flask-admin](https://flask-admin.readthedocs.io/en/latest/introduction/?highlight=bootswatch+theme#initialization)
* documenting the variable in bukuserver readme (including the mention of the most decent-looking dark theme)
> [bukuserver] Themes

- bukuserver/views.py
fixes #646:
* moving success logic on save (caching saved ID in session dict or raising an error on failure) out into a separate method
* using said method in both create and update handlers to handle save logic  
_note: flask-admin handles edit errors differently in debug and production mode_
> [bukuserver] Bookmark update error message

- bukuserver/templates/bukuserver/lib.html
fixes #658:
* adding manual popup window check to `close_if_popup()` macro (instead of relying on browser check)
> [bukuserver] New tab bug fix

- buku
- bukuserver/api.py
- bukuserver/views.py
- requirements.txt
- setup.py
- tests/test_buku.py
- tests/test_bukuDb.py
fixes #648:
* implementing general-purpose private methods in `BukuDb` for fetching all/one bookmark (the latter returns `None` as empty result)
* changing `BukuDb` code to use these fetch methods where applicable, replacing `-1` result with `None` when an ID is returned
* changing library, server & test code to handle the `None` results
fixes #654:
* changing `BukuDb` methods returning a list to always return a list (instead of returning `None` occassionally)
* simplifying the handling of these results
fixes #652:
* replacing `BookmarkVar` definition with a typed namedtuple
* converting bookmark values from the database into `BookmarkVar`s
* replacing tuple index access via magic numbers with named field access for `BookmarkVar`s
fixes #653:
* removing `Optional[]` type hint where it's …
> [bukudb] Various improvements

- bukuserver/views.py
The data rendered on page should be escaped to avoid evaluating it as HTML (and potentially JS)
> [bukuserver] Escaping markup

- .circleci/config.yml
- bukuserver/views.py
As per discussion in f00348e & #676
> fixed linter warnings & moved linting to a separate CI job

- .circleci/config.yml
- .gitignore
- tests/test_bukuDb.py
- tox.ini
As per discussion [here](https://github.com/jarun/buku/commit/aa3606d4f2760350706ae5ae97a65cd015d20215#commitcomment-125638115).
`pylint` fails due to being run on Python 3.7 image (there might be a bug in `pip` involved, as it delves into an infinite recursion when trying to resolve deps, but ultimately it shouldn't be run on an outdated runtime in the first place).
Unit tests seem to be failing due to conflicting DB file access. Using the `setup` fixture appears to resolve the immediate issue, but I strongly suggest switching as many tests as possible to an [in-memory DB](https://www.sqlite.org/inmemorydb.html) (this can be supported by setting custom logic for `dbfile == ''` in `BukuDb.initdb()`, then simply making a fixture that produces `BukuDb(dbfile='')`).
> fixed CI pylint & Python 3.11 testing runs

- .circleci/config.yml
- .gitignore
- bukuserver/server.py
- bukuserver/static/bukuserver/js/last_page.js
- bukuserver/templates/bukuserver/home.html
- bukuserver/views.py
- setup.py
- tests/test_bukuDb.py
- tests/test_views.py
- tox.ini
automates a part of [these](https://github.com/jarun/buku/wiki/PR-guidelines#testing-bukuserver) tests (by examining response HTML):
* the bookmarklet popup form
* bookmark editing forms
* [configurable functionality](https://github.com/jarun/buku/tree/master/bukuserver#configuration)
also:
* changing the views to access runtime values of `BUKUSERVER_PER_PAGE` & `BUKUSERVER_URL_RENDER_MODE` instead of memorising initial ones
* simplifying `last_page()` logic
> [bukuserver] functional tests

- bukuserver/README.md
- bukuserver/requirements.txt
- bukuserver/server.py
- setup.py
Updating `BUKUSERVER_LOCALE` support to match [the latest release of flask-admin](https://github.com/flask-admin/flask-admin/blob/v1.6.1/flask_admin/babel.py#L2-L5)
> [bukuserver] added support for flask-babel

- buku
- bukuserver/requirements.txt
- setup.py
- tests/test_bukuDb.py
- tests/test_views.py
fixes #698:
* adding a limit on `werkzeug` library version (dependency of Flask-API) to fix compatibility problems
* moving `return` statements out of the (unnecessary) `finally:` blocks
also:
* modifying tests to avoid unnecessary network requests (this was causing very long freezes in some tests)
> [jarun#698] fixed dependencies & improved testing time

- buku
- bukuserver/api.py
- bukuserver/forms.py
- bukuserver/response.py
- bukuserver/server.py
- bukuserver/views.py
- tests/test_bukuDb.py
- tests/test_server.py
Addresses most comments made by @LeXofLeviafan  in [issue #672](https://github.com/jarun/buku/issues/672)
1. `ApiTagView.put()` (PUT `/api/tags/<tag>`) now expects a list of strings as arguments instead of a comma-separated string. Passing an empty list results in bad response 400.
2. A separate `ApiTagView.delete()` method was added to delete an existing tag (DELETE `/api/tags/<tag>`).
3. A trailing slash is now permitted on  `GET /api/tags/` route.
ORIGINAL DESCRIPTION
_0. Clarify the expected data type received in ApiTagView.put:
PUT /api/tags/<tag> now returns 400 if no string is passed as input data
1. Allow `ApiTagView.put()` to update an existing tag with multiple ones by passing a single, comma-separated string. Instead of modifying the behavior of `replace_tag()`, which in my …
> [bukuserver API] improve tag replacement/deletion

- buku
- requirements.txt
- setup.py
- tests/test_bukuDb.py
- tox.bat
- tox.ini
fixes #704:
* fixing error caused by I/O stream manipulation in `browse(url)` on Windows 11
also:
* fixing color support on Windows 7-10
* fixing tests to work on Windows (full `tox` run now succeeds on Windows 7-11… though I'm not actually sure how exactly this works on Windows 7 considering that it's no longer supported by CPython 3.9+ :sweat_smile:)
* fixing unregistered Pytest marker warning when running tests in Tox
* fixing [deprecation warning for `text` argument of BeatifulSoup `.find*()` methods](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#the-string-argument)
> [jarun#704] fixed Windows support

- buku
- tests/test_buku.py
fixes #713:
* replacing the code [that always returns `utf-8`](https://beautiful-soup-4.readthedocs.io/en/latest/#output-encoding) with [BeautifulSoup implementation of charset detection](https://pydocbrowser.github.io/beautifulsoup4/latest/bs4.dammit.EncodingDetector.html#find_declared_encoding)
> [jarun#713] fixed HTML encoding detection

- buku
- buku.1
- tests/test_buku.py
- tests/test_bukuDb/25491522_res.yaml
- tests/test_bukuDb/Bookmarks
fixes #711:
* changing Firefox profile detection from single to multiple when multiple installs are found (asking which one to pick until one is chosen)
* adding support for environment variable (`FIREFOX_PROFILE`) in CLI & parameter (`firefox_profile`) in API
also:
* skipping nonexistent bookmark files
* stripping commas (tag delimiter) from imported tags (particularly parent folder ones)
> [jarun#711] fixed profile detection for multiple Firefox installs

- buku
Just a small UX improvement for some people (that includes me). ref.: https://no-color.org
> Support NO_COLOR

- buku
fixes #729:
* value of the default `url` parameter of `update_rec()` passed from CLI should be `None`, not `''`
> [jarun#729] fixed url value passed to update_rec() from CLI

- .circleci/config.yml
- bukuserver/api.py
- bukuserver/views.py
- setup.py
- tox.ini
I have migrated the [brew build into py3.12](https://github.com/Homebrew/homebrew-core/pull/150977), and it works out fine, thus adding the support in here as well.
> ci: add py3.12 support

- bukuserver/api.py
- bukuserver/views.py
- tests/test_views.py
- tox.ini
I couldn't manage to reproduce the warnings locally… ~~I wonder what's causing the difference :thinking:~~ Turns out pylint misses some checks when it doesn't have access to sources of imported modules. (…Also it only works with Python **3.12** for some reason.)
> fix pylint warnings by fixing a test

- buku
It appears to be a recent addition to `pylint`.
> fix lint warning E0606: possibly-used-before-assignment

- buku
- tests/test_bukuDb.py
…Turns out there's a but in the committed version of that function :sweat_smile:
Added a test case to ensure it actually works as expected.
(See #741 for the linting error.)
> fixed get_rec_all_by_ids

- README.md
- buku
- buku.1
- tests/test_buku.py
When exporting to a file ending with `.rss`, buku will now generate an RSS feed compatible with RSS readers. The feed encodes each bookmark as an entry with `<title>`, `<url>`, `<conent>` and `<category>` elements.
The feed generated right now is an Atom feed. 
Tested both import and export with: `buku -e bk.rss` and `buku -i bk.rss`
Tested feed validity using [newsboat](https://newsboat.org/index.html) and opening it in Brave browser.
> Add RSS import/export

- bukuserver/README.md
- bukuserver/requirements.txt
- bukuserver/server.py
- setup.py
* blocking `flake-admin` v2 until able to migrate properly when it's released (see #753)
* fixing outdated install instructions in bukuserver readme (e.g. `[reverse_proxy]` flag – see #722)
> [jarun#753] temporarily block flake-admin-v2 & actualize install instructions

- buku
- setup.py
- tests/pytest.ini
- tox.ini
…So I've been working on [Bootstrap v4 migration](https://github.com/jarun/buku/issues/753) (…as much as my free time permitted), and encountered [a bug that caused every new modal to send _twice as many fetch requests as the previous one when being opened_](https://github.com/pallets-eco/flask-admin/issues/2406). This exposed a problem in the main Buku library: **it's not threadsafe**. (More specifically, dealing with two simultaneous web-requests causes an error, and having more than that results in an immediate segfault.)
Hence, I've added a [repeating-lock](https://docs.python.org/3/library/threading.html#threading.RLock) to handle concurrent access (it doesn't interfere with same-thread actions, thus only affecting the cases when the library is used from multiple threads at once), …
> [jarun#753] implement thread safety

- README.md
- bukuserver/README.md
- docs/source/tutorial_for_developer.md
Since bukuserver screenshots will become outdated after migrating to Bootstrap v4 (at least both `default` and `slate` themes are visibly different from their v3 counterparts), I decided to copy the changes from #657 (on which there had been no activity _for a year and a half_ by now, incidentally) and do the requested changes myself.
I addressed the versioning issue (as well as some accessibility issues caused by relying on Imgur) via creating [a repo for storing documentation assets](https://github.com/Buku-dev/buku-docs); all images (and image links) are now versioned via tags. I split the changes in 2 commits: first to make the switch (using current repo screenshots), and the second contains changes from the original pull-request (including the new screenshot… or rather its cropped …
> bukuserver readme update

- bukuserver/filters.py
- bukuserver/views.py
<details><summary>tag name search</summary>
</details>
<details><summary>bookmark URL search</summary>
</details>
<details><summary>bookmark title search</summary>
</details>
> added contains/not-contains filter types

- buku
- tests/test_buku.py
When trying to import [a generated DB file](https://gist.github.com/LeXofLeviafan/47def9c55ee9107680e7790c86e07453), I've noticed some irregularities. I went around the issue by converting the file to [Markdown format](https://gist.github.com/LeXofLeviafan/fbc4c88e3db22c3c080c1ea81d0ae16e), but I still ended up making a few improvements to the parsing code; namely:
* reimplemented Markdown/OrgMode parsing via regex
* added support for "raw links" (`<url>`/`[[url]]`)
* added tests for all valid _and invalid_ link formats (based on which formats Pandoc can handle, and treating blank links as "always invalid")
<details><summary><h2>Markdown import</h2></summary>
```markdown
* [Bookmark title](http://example.com/1) 
* [Bookmark title](javascript:void(2))   
* [Bookmark title]() …
```
> improved markdown & orgmode parsing

- bukuserver/templates/bukuserver/bookmark_create.html
- bukuserver/templates/bukuserver/bookmark_details.html
- bukuserver/templates/bukuserver/bookmark_edit.html
- bukuserver/templates/bukuserver/lib.html
Come to think of it, the bookmarklet popup window is not a good place to open other pages in; so we should override `BUKUSERVER_OPEN_IN_NEW_TAB` inside popups.
> ensuring that popup links always open externally

- bukuserver/requirements.txt
- bukuserver/static/bukuserver/css/bookmark.css
- bukuserver/templates/bukuserver/bookmark_details.html
- bukuserver/templates/bukuserver/lib.html
- bukuserver/views.py
- setup.py
After some more fiddling I decided to move the URL enhancement of the details view to the backend, along with enhancing other fields as well (similar to the bookmarks list view).
* tags are rendered as badges (functioning as clickable filters)
+ edge cases are handled correctly
+ also applies to the input form
* favicon is displayed (if enabled) before the URL; it doubles as a netloc filter
+ when favicons are disabled, displaying a regular netloc badge instead
* description is rendered with preserved spacing
…And yes, within a popup all these links will get opened externally.
> improving bookmark details view

- buku
- tests/test_buku.py
- tests/test_bukuDb.py
- tests/test_cli.py
- tests/util.py
Addressing the case discussed in #759
* When running an `--add` command, tag lists supplied via `--tag` or `--add` (2nd value and further) can be prepended with `+` or `-`, same as when editing tags
* `+` means tags in the list should be included in the resulting record tags
* `-` means tags in the list should be _excluded_ from the resulting record tags (this is applied last)
* If either of the tag lists is non-empty (even if it's just a `,` or a blank string), but doesn't start with `+`/`-`, it has same effect as `+` except it _overrides_ fetched tags
* These rules apply to both tag lists identically (if both/neither start with `-`, they're simply combined)
* If there's no reason to fetch remote data (i.e. user supplied title and description, applied tags override, and did not request …
> support overriding fetched tags when adding a bookmark

- README.md
- buku
- buku.1
- bukuserver/filters.py
- bukuserver/forms.py
- bukuserver/static/bukuserver/css/list.css
- bukuserver/static/bukuserver/js/buku_filter.js
- bukuserver/templates/bukuserver/bookmarks_list.html
- bukuserver/templates/bukuserver/home.html
- bukuserver/views.py
- tests/test_buku.py
- tests/test_bukuDb.py
- tests/test_cli.py
fixes #740:
* adding an option to enable "search-with-markers", wherein each keyword can be applied to a specific field instead of all fields (based on keyword prefix: `.` for title, `>` for description, `:` for URL, `#` for tags; `*` or no prefix for all fields)
* implementing support for it via CLI (`--markers`), interactive shell (`m`), bukuserver `buku` filter mode (`markers*`), bukuserver index page/navbar search
* updating user manuals accordingly
also:
* adding support for specifying the bookmarks output sorting order (as appropriate)
* implementing support for it via CLI (`--order`), interactive shell (`v`… more fitting letters are taken already :sweat_smile:), bukuserver bookmarks filter (`order`); + a `BukuDb` method for sorting already fetched bookmarks (with matching …
> implementing search-with-markers

- README.md
- buku
- buku.1
- bukuserver/server.py
- bukuserver/templates/bukuserver/bookmark_details_modal.html
- bukuserver/templates/bukuserver/bookmarks_list.html
- bukuserver/util.py
- bukuserver/views.py
- tests/test_bukuDb.py
- tests/test_cli.py
- tests/test_views.py
Ability to poll for a random bookmark (without immediately opening it in a browser).  
Usecase: “what do I read next?” (+bukuserver)
<details><summary>CLI</summary>
(can be used with print, search and export)
</details>
<details><summary>interactive shell</summary>
(`R` shows a random result, `R 3` – 3 results, `R -2` shows 2 random records ignoring last/current search)
</details>
<details><summary>webUI</summary>
(the Random button searches within currently viewed list)
(the "Pick another" button is only present when viewing a random entry; it refreshes the modal contents which rerolls the ID)
(the View Record header link is identical to the one used in "successful update" message; it's handy if you want to edit a [random] entry, and then switch back to the list you were viewing) …
> implementing random bookmark(s) selection

- buku
- tests/test_buku.py
- tests/test_cli.py
fixes #783:
* end-ranges (e.g. `-3`) are now usable again in `--print` arguments
* also fixed for `p` arguments in the interactive shell
> fixing index end-ranges in --print arguments

- .circleci/config.yml
- buku
- setup.py
- tox.ini
resolves #780:
* added Python 3.13 to package setup file, as well as `tox` & CI configs
* removed Python 3.8 from those same files
I did not switch default `tox` Python version from 3.12 yet since both 3.12 & 3.13 have the same official status but 3.13 was only recently released. (The tests with `-e py313` seem to be running alright locally though.)
> Updating supported Python versions

- buku
- tests/test_buku.py
fixes #791:
* when processing paths for Firefox autoimport, absolute paths are now handled correctly (whether taken from `profiles.ini` or supplied with `FIREFOX_PROFILE=`)
Also cleaned up some duplicate code in `.auto_import_from_browser()`.
> [jarun#791] added support for absolute paths in Firefox autoimport

- bukuserver/api.py
- bukuserver/templates/bukuserver/bookmark_create.html
- bukuserver/templates/bukuserver/bookmark_create_modal.html
- bukuserver/views.py
- tests/test_views.py
Something which I had in my workspace for a week or so…
This doesn't affect current Bukuserver behaviour, but it extends the bookmarklet API to support all fields of the Create Bookmark form; which could be used by custom (e.g. user-made) bookmarklets.
> added support for all form parameters in bookmarklet endpoint

- buku
- tests/test_cli.py
fixes #796:
* the `--db=` argument is now passed to `BukuCrypt.encrypt_file()`/`.decrypt_file()` calls (when invoked from CLI via `--lock`/`--unlock`)
> [jarun#796] fixed DB not being passed to BukuCrypt from CLI

- bukuserver/README.md
- bukuserver/server.py
- bukuserver/views.py
- tests/test_views.py
Adding a "hybrid" option for `BUKUSERVER_URL_RENDER_MODE=` setting (it's effectively identical to `netloc`, except that the netloc-filter link is rendered as a "tag" – just like when using the `full` option). …It just looks cleaner, IMO.
@jarun alternatively we could replace the `netloc` option with this – it does pretty much the exact same thing, after all; just retaining design used by the other option for the same element.
The other options still work as before:
<details><summary><code>full</code>/unset</summary>
</details>
<details><summary><code>netloc</code></summary>
</details>
> added 'netloc-tag' to URL_RENDER_MODE values

- bukuserver/filters.py
…turns out they were broken (e.g. picking "index > in list" causes HTTP 500) :sweat_smile:
> fixed broken list filters in bookmarks

- buku
- tests/test_buku.py
fixes #807:
* when "add single, direct parent folder" tagging mode is enabled, the import behaves consistently with the "add all parent folders" mode (i.e. it applies parent tag to _**all**_ immediate children, not just the _**first one**_)
<details><summary>input file</summary>
```html
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>Bookmarks</TITLE>
<H1>Bookmarks</H1>
<DL><p>
<DT><H3>Testing</H3>
<DL><p>
<DT><H3>Testing Nested</H3>
<DL><p>
<DT><H3>Testing Nested Nested</H3>
<DL><p>
<DT><H3>Test</H3>
<DL><p>
<DT><A HREF="https://en.wikipedia.org/wiki/Main_Page#/media/File:The_Death_of_General_Mercer_at_the_Battle_of_Princeton_January_3_1777.jpeg">The Death of General Mercer at the Battle of Princeton January 3 1777 - …
```
> [jarun#807] fixed import in single-parent-folder-tag mode

- README.md
- buku
- buku.1
- tests/test_bukuDb.py
Hi, I often find myself having to scroll back and forth the results, but the program won't let me.
It would be great if you merged this into upstream, so I don't have to maintain my own patches.
If you intend to proceed, I'll update `buku.1` and `prompt_help` accordingly.
Thank you!
> Implement backwards navigation by pressing N

- README.md
- buku
- buku.1
- bukuserver/response.py
- bukuserver/server.py
- tests/test_bukuDb.py
- tests/test_server.py
- tests/test_views.py
fixes #815:
* removing broken functionality that relied on the decommissioned tny.im service
> Removing URL shorten/expand functionality

- Dockerfile
fixes #810:
* Docker healthcheck now reports working server as healthy
(before)
(after)
> Fixing docker healthcheck

- buku
- bukuserver/server.py
- bukuserver/templates/bukuserver/bookmark_create.html
- bukuserver/templates/bukuserver/bookmark_details.html
- bukuserver/templates/bukuserver/bookmark_edit.html
- bukuserver/templates/bukuserver/bookmarks_list.html
- bukuserver/templates/bukuserver/home.html
- bukuserver/templates/bukuserver/lib.html
- bukuserver/templates/bukuserver/tag_edit.html
- bukuserver/templates/bukuserver/tags_list.html
After adding [the ability to select/switch DB easily when using Bukuserver](https://github.com/jarun/buku/wiki/Bukuserver-(WebUI)#runner-script), it became possible for the user to forget which DB is being used at the moment. Because of that, I've added a few improvements:
* implementing `.dbfile` & `.dbname` properties in `BukuDb`
* allowing to check DB name in Bukuserver by hovering the `.navbar-brand` element
* displaying DB name clearly in popup windows
* displaying full DB path in tooltip when hovering the DB name (the cursor is set to `help` to indicate existence of the tooltip)
(unhovered logo)
(hovered logo)
(in a popup window)
> [Bukuserver] DB name display

- README.md
- buku
- buku.1
- bukuserver/api.py
- bukuserver/views.py
* implementing a `retained_order` parameter for deletion-related operations (when truthy, `compactdb()` updates multiple record indices at once in a way that prevents their reordering)
* adding a `--retained-order` CLI option to allow for using said functionality from CLI  
(...there doesn't seem to be any deletion support in the interactive shell :thinking:)
* changing Bukuserver to use this functionality by default
* fixing a bug in `delete_resultset()`
* ensuring that DB file is resized when committing (batch) deletions
* additionally, fixing text wrapping during record printing (for proper output of multiline descriptions, and to allow for linebreaks _between_ tags instead of hyphens)
@jarun honestly, I'd say it would make sense to _always_ retain ordering in CLI deletions as well, …
> support for retaining bookmarks order on deletion + printing multiline descriptions

- .circleci/config.yml
- README.md
- buku
- buku.1
- tox.ini
This implements DB switching functionality (based on [Bukuserver runner script](https://github.com/jarun/buku/wiki/Bukuserver-(WebUI)#runner-script)) within the interactive shell. Additionally it includes support for switching current folder (based on concerns mentioned in #821), and displays DB name in the prompt _unless it's the default DB_.
@jarun I'd say with these changes it should be safe to start interactive shell for a non-default DB (e.g. via `--db` or an env var like it's done in Bukuserver); what do you think?
Usage examples: print DB list, switch DB by specifying name / folder / folder+name / default DB shortcut
Custom extension & invalid location examples
> [buku shell] DB switching support

- buku
- buku.1
- bukuserver-runner/README.md
- bukuserver-runner/buku-server.py
- tests/test_cli.py
This complements [the previously added DB switching functionality in the interactive shell mode](https://github.com/jarun/buku/pull/823).
* default DB directory can be now overridden directly by specifying `BUKU_DEFAULT_DBDIR` environment variable (instead of [having to rely on workarounds](https://github.com/jarun/buku/issues/821))
* if the argument passed to `--db` contains neither `.` nor the directory separator, it's treated as DB _name_ (and resolved as a file of the same name with extension `.db`, within the default DB directory)
* `--db` can be used now to invoke interactive shell mode
* if `--db` is the only CLI argument (without a parameter), the program now simply prints out the list of databases in default DB directory (similarly to `DB` command in the interactive shell mode) …
> [buku CLI] improved --db & added BUKU_DEFAULT_DBDIR

- bukuserver/api.py
- bukuserver/server.py
- bukuserver/templates/bukuserver/lib.html
- tests/test_views.py
fixes #825
Since `opener` is not available when the popup is opened from a page fetched with `Cross-Origin-Opener-Policy: same-origin` response header (and there's no other reliable frontend-side way of detecting that the page was loaded in a popup), I've ended up implementing an extra request parameter: `popup=True`.
It's added to URLs that the bookmarklet handler redirects to, used to determine if the current page is a popup, and is persistently retained by (internal) requests from bookmark forms (which are supposed to be the only pages accessible from within the bookmarklet popup).
The following pages were tested:
* opening the popup for a new bookmark
* opening the popup for an existing bookmark
* switching between edit/details tabs for an existing bookmark (the window is still …
> Fixing popup detection for sites that prevent exposing opener

- bukuserver/views.py
- tests/test_views.py
fixes #828
Since the issue is _not_ exclusive to URLs without titles, I abandoned my original idea of replacing "&lt;EMPTY TITLE&gt;" with the URL text, and instead simply changed rendering logic so that the title link only gets disabled in `full` mode (…where it's not really needed in the first place, since the same hyperlink with URL text is rendered immediately below it). I've also added a tooltip with the URL to the title, so that before the user clicks on a link he'll have a chance to check it first.
<details><summary><code>BUKUSERVER_URL_RENDER_MODE=full</code></summary>
(before)
(after)
</details>
<details><summary><code>BUKUSERVER_URL_RENDER_MODE=netloc-tag</code></summary>
(before)
(after)
</details>
<details><summary><code>BUKUSERVER_URL_RENDER_MODE=netloc</code></summary> …
> Fixing rendering no-netloc URLs in non-full modes

- buku
- bukuserver/requirements.txt
- bukuserver/response.py
- bukuserver/server.py
- bukuserver/views.py
- requirements.txt
- setup.py
- tests/cassettes/test_buku/test_fetch_data_with_url[http---example.com-exp_res1].yaml
- tests/cassettes/test_buku/test_fetch_data_with_url[https---www.google.ru-search~-exp_res6].yaml
- tests/test_server.py
resolves #830:
* removing Flask-API usages & dependency (…we do not actually seem to be doing much with it to begin with :thinking:)
resolves #776:
* removing dependency on `werkzeug<2.4` & `flask<2.3` + changing dependency on `urllib3` from `<2` to `<3` (…seems like Flask-API was the primary limiter here after all :sweat_smile:)
Also, fixing some (all?) deprecation warnings printed when running tests.
(Note: checked WebUI and API – both seem to be working alright after these changes; and of course tests cover quite a few cases here.)
> Removing Flask-API

- bukuserver/README.md
- bukuserver/server.py
Nothing fancy here, just duplicating for Bukuserver the logic added to `--db` in #824
This can be useful when invoking Bukuserver manually (…which I only do for dev purposes, but it's more likely to be useful for regular users :sweat_smile:)
…Also added a link to the Wiki in Bukuserver readme (so that the users interested in Bukuserver have a better chance of finding out there's a runner to begin with)
> [Bukuserver] support for specifying DB name

- buku
- tests/test_buku.py
fixes #837:
* `if not None` condition (_always_ evaluates to `False`)
* concatenating a list with a string (would result in `TypeError`)
…Seriously, how was this bug never discovered for 8 years of its existence?! 🫠
> incorrect expression in to_temp_file_content()

- bukuserver-runner/buku-server.py
Turns out specifying `BUKU_VENV` with a `~` token in `bukuserver.env` (used with the runner script) can cause issues. This mitigates them.
> [Bukuserver] handling of HOME token within venv path

- bukuserver/api.py
- tests/test_bukuDb.py
- tests/test_server.py
- tests/test_views.py
After a recent update, `pytest` started producing warnings about unclosed DB connections during testing on Python 3.13:
> fix ResourceWarning messages on Python 3.13

- bukuserver/templates/bukuserver/bookmarks_list.html
- bukuserver/templates/bukuserver/lib.html
…Turns out it was not even showing when using a custom locale :sweat_smile:
<details><summary><h3>Screenshots</h3></summary>
(before)
(after)
(the form data is also submitted correctly)
</details>
> [Bukuserver] reorder button i18n bug fix
